# Configurazione base
quarkus.application.name=api-gateway
quarkus.http.port=8082

# Configurazione client per il servizio contatti
%dev.contact-api/mp-rest/url=http://localhost:8080
%prod.contact-api/mp-rest/url=http://${CONTACT_SERVICE_HOST:contact-service}:${CONTACT_SERVICE_PORT:8080}
contact-api/mp-rest/scope=jakarta.inject.Singleton

# Configurazione client per il servizio eventi
%dev.event-api/mp-rest/url=http://localhost:8081
%prod.event-api/mp-rest/url=http://${EVENT_SERVICE_HOST:event-service}:${EVENT_SERVICE_PORT:8080}
event-api/mp-rest/scope=jakarta.inject.Singleton

# Configurazione timeout
quarkus.rest-client.connect-timeout=10000
quarkus.rest-client.read-timeout=10000

# Documentazione OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger
quarkus.swagger-ui.always-include=true

# Configurazione CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS